server:
  port: 8080


spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: sentence
          uri: lb://sentence
          predicates:
            - Path=/
          filters:
            - name: CircuitBreaker
              args:
                name: sentenceCircuitBreaker
                fallbackUri: forward:/fallback/sentence

        - id: subject
          uri: lb://subject
          predicates:
            - Path=/subject
          filters:
            - SetPath=/
            - name: CircuitBreaker
              args:
                name: subjectCircuitBreaker
                fallbackUri: forward:/fallback/subject

        - id: verb
          uri: lb://verb
          predicates:
            - Path=/verb
          filters:
            - SetPath=/
            - name: CircuitBreaker
              args:
                name: verbCircuitBreaker
                fallbackUri: forward:/fallback/verb

        - id: object
          uri: lb://object
          predicates:
            - Path=/object
          filters:
            - SetPath=/
            - name: CircuitBreaker
              args:
                name: objectCircuitBreaker
                fallbackUri: forward:/fallback/object

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
        web:
          server: trace
eureka:
  client:
    service-url:
      default-zone: http:localhost:8761/eureka

  instance:
    hostname: host.docker.internal